name: Test renovate.json configuration
on:
  - pull_request

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Installation
        run: pnpm install 

      - name: Test
        run: pnpm run validate:renovate
