name: Test renovate.json configuration
on:
  - pull_request

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Installation
        run: npm install 

      - name: Test
        run: npm run validate:renovate
